#ifndef CONFIG_YU_H
#define CONFIG_YU_H

#undef MOUSEKEY_TIME_TO_MAX
#undef MOUSEKEY_MAX_SPEED

#define MOUSEKEY_TIME_TO_MAX 10
#define MOUSEKEY_MAX_SPEED 3

#define PREVENT_STUCK_MODIFIERS

#undef ONESHOT_TIMEOUT

#define ONESHOT_TIMEOUT 1000

#undef DEBOUNCE
#define DEBOUNCE 15

#endif
